#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Usage: ./run [server|client]"
    exit 0
fi

if [ $1 = "server" ]; then
    cd server
    python3 app.py
elif [ $1 = "client" ]; then
    cd client
    npm start
else
    echo "Unrecognised control"
fi